<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Bug on Norwegian Wood</title>
    <link>https://akynazh.site/categories/bug/</link>
    <description>Recent content in Bug on Norwegian Wood</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>zh-cn</language>
    <managingEditor>akynazh@qq.com (Jzh)</managingEditor>
    <webMaster>akynazh@qq.com (Jzh)</webMaster>
    <copyright>Jzh</copyright>
    <lastBuildDate>Fri, 04 Nov 2022 22:53:34 +0800</lastBuildDate><atom:link href="https://akynazh.site/categories/bug/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>Python 开发中遇到的 bug 记录</title>
      <link>https://akynazh.site/posts/2022/11/record-of-bugs-encountered-in-python-development/</link>
      <pubDate>Fri, 04 Nov 2022 22:53:34 +0800</pubDate>
      <author>akynazh@qq.com (Jzh)</author>
      <guid>https://akynazh.site/posts/2022/11/record-of-bugs-encountered-in-python-development/</guid>
      <description>持续更新中。
包冲突 1root@Server-Debian-Jzh:~/Codes/tg-jav-bot# python3 bot.py 2Traceback (most recent call last): 3 File &amp;#34;/root/Codes/tg-jav-bot/bot.py&amp;#34;, line 13, in &amp;lt;module&amp;gt; 4 import utils.util_javbus as util_javbus 5ModuleNotFoundError: No module named &amp;#39;utils.util_javbus&amp;#39;; &amp;#39;utils&amp;#39; is not a package 项目下的 utils 文件夹 &amp;lt;-&amp;gt; pip 某个依赖包中的 utils.py 文件名 &amp;ldquo;utils&amp;rdquo; 冲突！
默认先扫描当前目录下包，但是识别不到 utils 包，因为 utils 文件夹下缺失了 __init__.py 文件！
SSLError(SSLCertVerificationError) 使用 requests 库时出现 bug:
1(Caused by SSLError(SSLCertVerificationError(1, &amp;#39;[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)&amp;#39;))) 解决方法：python-requests-throwing-sslerror</description>
    </item>
    
  </channel>
</rss>